name: Run Bandit

on:
  push:
    branches:
      - main

jobs:
  bandit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  # Replace with the appropriate Python version

    - name: Install Bandit
      run: |
        python -m pip install --upgrade pip
        pip install bandit

    - name: Run Bandit
      run: bandit -r Chatbot_PD/main.py
