name: ZAP Security Scan

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Java 11
      run: |
        sudo apt-get -y install openjdk-11-jdk
        java -version
      shell: bash

    - name: Run ZAP Scan
      run: |
        wget https://github.com/zaproxy/zaproxy/releases/download/v2.10.0/ZAP_2.10.0_Core.zip
        unzip ZAP_2.10.0_Core.zip
        cd ZAP_2.10.0
        ./zap.sh -daemon -port 8080 -host 0.0.0.0 -config api.disablekey=true
        ./zap-cli --zap-url http://localhost:8080 -p 8080 quick-scan --self-contained "https://khaanvaani.streamlit.app/"
      env:
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64

    - name: Publish ZAP Scan Results
      run: |
        mkdir -p ${{ github.workspace }}/zap-reports
        mv alerts.json ${{ github.workspace }}/zap-reports
        echo '::set-output name=ZAP_SCAN_REPORT_PATH::zap-reports/alerts.json'
      working-directory: ${{ runner.workspace }}

    - name: Upload ZAP Scan Report
      uses: actions/upload-artifact@v2
      with:
        name: zap-reports
        path: ${{ github.workspace }}/zap-reports
